---
abstract: 'IO::Async event loop support for POE'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  POE::Test::Loops: 1.035
configure_requires:
  ExtUtils::MakeMaker: 6.30
  POE::Test::Loops: 1.035
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Loop-IO_Async
requires:
  IO::Async: 0.42
  POE: 1.289
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/poe-loop-io_async
  repository: https://github.com/bingos/poe-loop-io_async.git
version: 0.004
